"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['SplitScreener.py']
DATA_FILES = [
    'setup.py', 'ss_classes.py', 'fusion_tool_generator.py',
    # images
    'images/SS_icon.png',
    'images/.DS_Store',
    'images/ss_logo_spaced.png',
    'images/icons',
    'images/render_button.png',
    'images/btn_render.png',
    'images/btn_render_flatter.png',
    # icons
    'images/icons/icn_rotateccw_state1.png', 
    'images/icons/icn_rotateccw_state3.png', 
    'images/icons/icn_rotateccw_state2.png', 
    'images/icons/icn_trash_state2.png',
    'images/icons/.DS_Store', 
    'images/icons/icn_trash_state3.png',
    'images/icons/icn_trash_state1.png',
    'images/icons/icn_fliph_state1.png', 
    'images/icons/lbracket2.png',
    'images/icons/icn_flipv_state1.png',
    'images/icons/icn_fliph_state2.png',
    'images/icons/icn_flipv_state3.png',
    'images/icons/lbracket1.png', 
    'images/icons/icn_flipv_state2.png',
    'images/icons/icn_fliph_state3.png', 
    'images/icons/icn_rotatecw_state1.png', 
    'images/icons/icn_rotatecw_state2.png',
    'images/icons/icn_rotatecw_state3.png', 
    'images/icons/icn_link_state1.png', 
    'images/icons/icn_link_state2.png', 
    'images/icons/icn_link_state3.png',
    # defaults
    'defaults/defaults.json',
    #fonts
    'fonts/Archivo_SemiExpanded-Light.ttf'
]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app','jinja2','pyperclip','Pillow'],
)
